spring:
  profiles:
    active: db, admin
  messages:
    encoding: UTF-8

swagger:
  enabled: true

server:
  port: 8080

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.liguang.rcs.admin:  DEBUG
    com.liguang.rcs:  ERROR
